data={
  "Facile": [
    {
      "0":
      {
        "question":"12 + 8 = ",
        "reponse":"20",
        "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-rsoRsZi9Cfan2zolqSihuCz6t0QNEIjVbA&usqp=CAU"
      }
    },
    {
      "1":
      {
        "question":"1 + 0 = ",
        "reponse":"1",
        "image":"val_image"
      }
    },
    {
      "2":
      {
        "question":"122 + 3 = ",
        "reponse":"125",
        "image":"val_image"
      }
    },
    {
      "3":
      {
        "question":"34 + 5 = ",
        "reponse":"39",
        "image":"val_image"
      }
    },
    {
      "4":
      {
        "question":"23 + 14 = ",
        "reponse":"37",
        "image":"val_image"
      }
    },
    {
      "5":
      {
        "question":"44 - 28 = ",
        "reponse":"16",
        "image":"val_image"
      }
    },
    {
      "6":
      {
        "question":"59 - 41 = ",
        "reponse":"18",
        "image":"val_image"
      }
    },
    {
      "7":
      {
        "question":"165 - 47 = ",
        "reponse":"118",
        "image":"val_image"
      }
    },
    {
      "8":
      {
        "question":"12 - 2 = ",
        "reponse":"10",
        "image":"val_image"
      }
    },
    {
      "9":
      {
        "question":"89 - 88 = ",
        "reponse":"1",
        "image":"val_image"
      }
    },
    {
      "10":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "11":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "12":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "13":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "14":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "15":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "16":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "17":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "18":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "19":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    }
  ],
  "Moyen": [
    {
      "0":
      {
        "question":"6 * 6 = ",
        "reponse":"36",
        "image":"val_image"
      }
    },
    {
      "1":
      {
        "question":"3 * 7 = ",
        "reponse":"21",
        "image":"val_image"
      }
    },
    {
      "2":
      {
        "question":"12 * 10 = ",
        "reponse":"120",
        "image":"val_image"
      }
    },
    {
      "3":
      {
        "question":"45 * 0 = ",
        "reponse":"0",
        "image":"val_image"
      }
    },
    {
      "4":
      {
        "question":"9 * 7 = ",
        "reponse":"63",
        "image":"val_image"
      }
    },
    {
      "5":
      {
        "question":"10 / 10 = ",
        "reponse":"1",
        "image":"val_image"
      }
    },
    {
      "6":
      {
        "question":"6 / 3 = ",
        "reponse":"2",
        "image":"val_image"
      }
    },
    {
      "7":
      {
        "question":"12 / 2 = ",
        "reponse":"6",
        "image":"val_image"
      }
    },
    {
      "8":
      {
        "question":"39 / 3 = ",
        "reponse":"13",
        "image":"val_image"
      }
    },
    {
      "9":
      {
        "question":"25 / 5 = ",
        "reponse":"5",
        "image":"val_image"
      }
    },
    {
      "10":
      {
        "question":"5 / 1 = ",
        "reponse":"5",
        "image":"val_image"
      }
    },
    {
      "11":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "12":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "13":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "14":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "15":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "16":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "17":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "18":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "19":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    }
  ],
  "Difficile": [
    {
      "0":
      {
        "question":"(5*10) + 4 - 2 = ",
        "reponse":"52",
        "image":"val_image"
      }
    },
    {
      "1":
      {
        "question":"4 + 12 + / 6 + 5 = ",
        "reponse":"11",
        "image":"val_image"
      }
    },
    {
      "2":
      {
        "question":"12 * 2 * 10 = ",
        "reponse":"120",
        "image":"val_image"
      }
    },
    {
      "3":
      {
        "question":"5 - 3 + 7 * 4 = ",
        "reponse":"30",
        "image":"val_image"
      }
    },
    {
      "4":
      {
        "question":"8 * 6 - 6 = ",
        "reponse":"42",
        "image":"val_image"
      }
    },
    {
      "5":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "6":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "7":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "8":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "9":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "10":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "11":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "12":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "13":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "14":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "15":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "16":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "17":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "18":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    },
    {
      "19":
      {
        "question":"val_question",
        "reponse":"val_reponse",
        "image":"val_image"
      }
    }
  ]
}

